### ISSUE TITLE
Is it possible to avoid opening the configuration window at every KDE startup?

### ISSUE THREAD

**Issue by jamadagni** [martenjj/wallpaperswitch#10]
Hello. Currently I'm autostarting wallpaperswitch by placing the following contents in a `wallpaperswitch.desktop` file under `~/.config/autostart`:

```
[Desktop Entry]
Comment[en_US]=
Comment=
Exec=/usr/local/bin/wallpaperswitch
GenericName[en_US]=
GenericName=
Icon=system-run
MimeType=
Name[en_US]=
Name=Wallpaper Switch
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=
X-KDE-SubstituteUID=false
X-KDE-Username=
```

However, it opens up the configuration window every time I login to KDE. Is there a way to avoid this? The app doesn't seem to have any command-line switches or at least there is no `-h`/`--help` option that lists them…

**Comment by martenjj** [comment]
There is nothing wrong with your autostart file, and no reason why it shouldn't work as intended.  There are no command line switches, but after the configuration dialogue has been shown on the first run (and assuming that you set up the wallpaper and accept the settings with "OK"), it should write the application configuration file ~/.config/wallpaperswitchrc (depending on your distro this location may vary, it will be in $XDG_CONFIG_HOME if that is set).  This file should include the section and config key:

   [Wallpaper]
   firstStartup=false

If this file does not exist or does not contain that value then check that XDG_CONFIG_HOME is correctly set and the permissions on that location allow writing.

**Comment by jamadagni** [comment]
Hi thanks for this reply. I do have a `wallpaperswitchrc` under `~/.config/` but I still was receiving the prompt. I also noticed that sometimes I had two icons in my tray and so removed the `.desktop` file from under `~/.config/autostart/` and now it's working fine.

But if I have removed it from `~/.config/autostart/` how does it autostart then? Have you configured a different location that is automatically setup on first use?

Thanks!

**Comment by frojack** [comment]
@jamadagni I would be willing to bet it is because you have KDE set to restore Previous Session in Startup and Shutdown in Kde Settings.

If that it set then it will restore everything that was running when you log in.
I prefer to set that to Restore Manually Saved Session.  After setting this, you will find Save Session appears in Power and Settings section of the KDE main menu.  Just set up the machine the way you want and click that.  Next time you log in, it will restart only those.  

You can of course remove wallpaper switcher from Auto Start in this case as well.

The other choice in that Same Desktop Session menu is Start with an Empty session.  This is probably the only place you would need to have Switcher in the Auto Start list.

**Comment by jamadagni** [comment]
Thank you for your reply. It seems quite logical. 💐

So I am now closing this issue.
