### ISSUE TITLE
Thank you for this nice option

### ISSUE THREAD

**Issue by phd21** [martenjj/wallpaperswitch#5]
Hi Jonathan Marten,

Thank you for this nice option.

I am using Linux Mint KDE 18.1 (Ubuntu 16.04 Plasma 5) and Linux Mint KDE 17.3 (Ubuntu 14.04 Plasma 4).  In Linux Mint 18.x Plasma 5 I really miss having the different wallpapers and different widgets (icons)  per virtual desktop without using "Activities". Now with your utility, I at least have the wallpapers back. :)

I did however have to install these before it would compile on my system.
extra-cmake-modules
libkf5crash-dev

Can you please make easy to install ".deb" files from this for 64-bit and 32-bit systems?

I tried "sudo dpkg-repack wallpaperswitch", but it did not work. Then, I tried "sudo checkinstall" from the "~/wallpaperswitch/build/src" and it did create a 64-bit deb file, but I do not yet have the experience to know if it is a good install file compared to compiling your code per your instructions.

Best regards to you and yours,
Phil
phd21

**Comment by martenjj** [comment]
Sorry, I don't run any Debian systems here and have no idea of what is involved to create a Debian package, either source or binary.  I'd guess that the latter at least would involve having to track dependencies, which I wouldn't be able to do effectively without having an up-to-date system in daily use (otherwise it would bitrot).  Sorry...
